apiVersion: v1
kind: Pod
metadata:
  name: dashboard-sa
spec:
  affinity:
    nodeAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
        - preference:
            matchExpressions:
              - key: size
                operator: In
                values:
                  - large
          weight: 100
  containers:
    - name: dashboard-sa
      image: busybox
      resources:
        limits:
          memory: "2G"
          cpu: "2"
        requests:
          memory: "1G"
          cpu: "1"
