apiVersion: v1
kind: Pod
metadata:
  name: simple-webapp
spec:
  containers:
    - name: simple-webapp
      image: simple-webapp
      ports:
        - containerPort: 8080
      readinessProbe:
        httpGet:
          path: /api/read
          port: 8080
        initialDelaySeconds: 10
        periodSeconds: 5
        failureThreshold: 8
