apiVersion: v1

kind: Pod

metadata:
  name: ubuntu-sleeper-pod

spec:
  containers:
    - name: ubuntu-sleeper-pod
      image: ubuntu-sleeper
      command: ["sleep"]
      args: ["10"]
      imagePullPolicy: Never
  restartPolicy: Never
